# Generated by Django 4.2.2 on 2023-07-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customer_default_country_alter_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="default_full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
