# Generated by Django 4.2.2 on 2023-07-08 01:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customer_default_full_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="default_full_name",
            new_name="full_name",
        ),
    ]
