# Generated by Django 4.2.2 on 2023-07-08 02:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_rename_default_full_name_customer_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="full_name",
        ),
    ]
