# Generated by Django 4.2.2 on 2023-07-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_customer_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
