# Generated by Django 4.2.2 on 2023-07-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_customer_first_name_customer_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(default="John", max_length=150),
            preserve_default=False,
        ),
    ]
