# Generated by Django 4.2.2 on 2023-07-09 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_customer_first_name_alter_customer_last_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="first_name",
            new_name="default_first_name",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="last_name",
            new_name="default_last_name",
        ),
    ]
