# Generated by Django 4.2.2 on 2023-07-10 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_rename_first_name_customer_default_first_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="default_first_name",
            new_name="default_full_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="default_last_name",
        ),
    ]
