# Generated by Django 4.2.2 on 2023-07-12 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0029_alter_album_popularity_alter_album_price"),
        (
            "accounts",
            "0011_rename_default_first_name_customer_default_full_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="products.album"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlists",
                        to="accounts.customer",
                    ),
                ),
            ],
            options={
                "unique_together": {("customer", "album")},
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="wishlist",
            field=models.ManyToManyField(
                blank=True, through="accounts.Wishlist", to="products.album"
            ),
        ),
    ]
