# Generated by Django 4.2.2 on 2023-07-12 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_wishlist_customer_wishlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="wishlist",
        ),
    ]
