# Generated by Django 4.2.2 on 2023-07-13 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0029_alter_album_popularity_alter_album_price"),
        ("accounts", "0016_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="products.album",
            ),
        ),
    ]
