# Generated by Django 4.2.2 on 2023-07-13 23:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_alter_review_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_text",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
