# Generated by Django 4.2.2 on 2023-07-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_albumrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="default_first_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="default_last_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
