# Generated by Django 4.2.2 on 2023-07-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_customer_default_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="albumrequest",
            name="request_title",
            field=models.CharField(default="TEST", max_length=200),
            preserve_default=False,
        ),
    ]
