# Generated by Django 4.2.2 on 2023-07-16 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_albumrequest_request_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="default_full_name",
        ),
    ]
