# Generated by Django 4.2.2 on 2023-07-17 01:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_remove_customer_default_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="role",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="user",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="Staff",
        ),
    ]
