# Generated by Django 4.2.2 on 2023-07-06 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "checkout",
            "0002_alter_order_delivery_cost_alter_order_order_number_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderlineitem",
            old_name="product",
            new_name="album",
        ),
        migrations.AddField(
            model_name="order",
            name="original_cart",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_pid",
            field=models.CharField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name="orderlineitem",
            name="lineitem_total",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name="orderlineitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lineitems",
                to="checkout.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderlineitem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
