# Generated by Django 4.2.2 on 2023-07-07 15:31

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0003_rename_product_orderlineitem_album_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=django_countries.fields.CountryField(
                max_length=2, verbose_name="Country"
            ),
        ),
    ]
