# Generated by Django 4.2.2 on 2023-07-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0006_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
