# Generated by Django 4.2.2 on 2023-07-10 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0009_order_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="last_name",
        ),
    ]
