# Generated by Django 4.2.2 on 2023-06-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "artist_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("genres", models.TextField(blank=True, null=True)),
                ("spotify_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_number", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("duration", models.CharField(blank=True, max_length=10, null=True)),
                ("explicit", models.BooleanField(blank=True, null=True)),
                ("spotify_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                ("total_tracks", models.IntegerField(blank=True, null=True)),
                ("popularity", models.IntegerField(blank=True, null=True)),
                (
                    "album_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("album_type", models.CharField(blank=True, max_length=100, null=True)),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
                ("copyright", models.CharField(blank=True, max_length=100, null=True)),
                ("explicit", models.BooleanField(blank=True, null=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("on_sale", models.BooleanField(blank=True, default=False, null=True)),
                ("spotify_url", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="album_images"),
                ),
                ("artists", models.ManyToManyField(to="products.artist")),
                ("tracks", models.ManyToManyField(to="products.track")),
            ],
        ),
    ]
