# Generated by Django 4.2.2 on 2023-06-22 21:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("on_sale", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TShirtSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="album",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.RemoveField(
            model_name="artist",
            name="genres",
        ),
        migrations.CreateModel(
            name="TShirt",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
            ],
            bases=("products.product",),
        ),
        migrations.AddField(
            model_name="album",
            name="genres",
            field=models.ManyToManyField(to="products.genre"),
        ),
        migrations.AddField(
            model_name="artist",
            name="genres",
            field=models.ManyToManyField(to="products.genre"),
        ),
        migrations.CreateModel(
            name="Vinyl",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="products.album"
                    ),
                ),
            ],
            bases=("products.product",),
        ),
        migrations.CreateModel(
            name="TShirtQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.tshirtsize",
                    ),
                ),
                (
                    "tshirt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.tshirt",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tshirt",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.album"
            ),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="sizes",
            field=models.ManyToManyField(to="products.tshirtsize"),
        ),
        migrations.CreateModel(
            name="CD",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="products.album"
                    ),
                ),
            ],
            bases=("products.product",),
        ),
    ]
