# Generated by Django 4.2.2 on 2023-06-23 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.IntegerField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="album",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="href",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="uri",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="artists",
            field=models.ManyToManyField(related_name="tracks", to="products.artist"),
        ),
        migrations.AddField(
            model_name="track",
            name="href",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="uri",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="explicit",
            field=models.CharField(
                blank=True,
                choices=[("E", "Explicit"), ("C", "Clean"), ("U", "Unknown")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="explicit",
            field=models.CharField(
                blank=True,
                choices=[("E", "Explicit"), ("C", "Clean"), ("U", "Unknown")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="external_urls",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.externalurl",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="external_urls",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.externalurl",
            ),
        ),
    ]
