# Generated by Django 4.2.2 on 2023-06-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0002_externalurl_image_album_name_artist_href_artist_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="duration",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
