# Generated by Django 4.2.2 on 2023-06-23 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_track_duration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="album",
            old_name="copyright",
            new_name="copyrights",
        ),
    ]
