# Generated by Django 4.2.2 on 2023-06-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_rename_copyright_album_copyrights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="explicit",
            field=models.BooleanField(null=True),
        ),
    ]
