# Generated by Django 4.2.2 on 2023-06-23 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_album_explicit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="album",
            old_name="name",
            new_name="album_name",
        ),
    ]
