# Generated by Django 4.2.2 on 2023-06-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_album_artist_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="release_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
