# Generated by Django 4.2.2 on 2023-06-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_album_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="artist_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
