# Generated by Django 4.2.2 on 2023-06-23 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_alter_album_artist_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="album",
            old_name="name",
            new_name="album",
        ),
    ]
