# Generated by Django 4.2.2 on 2023-06-28 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_remove_album_tracks_track_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="tracks",
            field=models.ManyToManyField(related_name="albums", to="products.track"),
        ),
        migrations.AlterField(
            model_name="track",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_set",
                to="products.album",
            ),
        ),
    ]
