# Generated by Django 4.2.2 on 2023-06-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_albumartist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="album",
            old_name="album",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="album",
            name="tracks",
            field=models.ManyToManyField(
                db_table="albums_tracks", related_name="albums", to="products.track"
            ),
        ),
    ]
