# Generated by Django 4.2.2 on 2023-06-28 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0018_remove_track_album_alter_album_tracks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="album",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_set",
                related_query_name="track",
                to="products.album",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="tracks",
            field=models.ManyToManyField(
                db_table="albums_tracks", related_name="albums", to="products.track"
            ),
        ),
        migrations.CreateModel(
            name="AlbumArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="products.album"
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.artist",
                    ),
                ),
            ],
        ),
    ]
