# Generated by Django 4.2.2 on 2023-06-29 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0019_track_album_alter_album_tracks_albumartist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="tracks",
        ),
        migrations.AlterField(
            model_name="track",
            name="album",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="products.album",
            ),
        ),
    ]
