# Generated by Django 4.2.2 on 2023-06-29 16:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0020_remove_album_tracks_alter_track_album"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AlbumArtist",
        ),
    ]
