# Generated by Django 4.2.2 on 2023-06-29 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0022_rename_name_album_album_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="track",
            old_name="name",
            new_name="track_name",
        ),
    ]
