# Generated by Django 4.2.2 on 2023-06-29 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0023_rename_name_track_track_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artist",
            old_name="name",
            new_name="artist_name",
        ),
        migrations.RenameField(
            model_name="cd",
            old_name="name",
            new_name="product_name",
        ),
        migrations.RenameField(
            model_name="tshirt",
            old_name="name",
            new_name="product_name",
        ),
        migrations.RenameField(
            model_name="vinyl",
            old_name="name",
            new_name="product_name",
        ),
    ]
