# Generated by Django 4.2.2 on 2023-07-01 17:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0025_rename_album_track_albums"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("25.00"), max_digits=6
            ),
        ),
    ]
