# Generated by Django 4.2.2 on 2023-07-10 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0026_album_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="album_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="copyrights",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="genres",
            field=models.ManyToManyField(
                db_index=True, related_name="albums", to="products.genre"
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="image_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.image",
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="artist_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
