# Generated by Django 4.2.2 on 2023-07-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0027_alter_album_album_name_alter_album_copyrights_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="album_id",
            field=models.CharField(default="ABCDE", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
