# Generated by Django 4.2.2 on 2023-07-12 13:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0028_alter_album_album_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="popularity",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("25.00"),
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
