# Generated by Django 4.2.2 on 2023-07-14 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_alter_review_review_text"),
        ("products", "0029_alter_album_popularity_alter_album_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="products.album"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                    ),
                ),
            ],
            options={
                "unique_together": {("customer", "album")},
            },
        ),
        migrations.AddField(
            model_name="album",
            name="customer_ratings",
            field=models.ManyToManyField(
                related_name="rated_albums",
                through="products.CustomerRating",
                to="accounts.customer",
            ),
        ),
    ]
