# Generated by Django 4.2.2 on 2023-07-15 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0031_remove_album_customer_ratings_delete_customerrating",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="main_artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_albums",
                to="products.artist",
            ),
        ),
    ]
