# Generated by Django 4.2.2 on 2023-07-15 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0032_album_main_artist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="main_artist",
        ),
    ]
