# Generated by Django 4.2.2 on 2023-07-15 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0033_remove_album_main_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="main_artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_albums",
                to="products.artist",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="album_id",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
