# Generated by Django 4.2.2 on 2023-07-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0034_album_main_artist_alter_album_album_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="external_urls",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.externalurl",
            ),
        ),
    ]
