# Generated by Django 4.2.2 on 2023-07-16 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0035_album_external_urls"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tshirt",
            name="album",
        ),
        migrations.RemoveField(
            model_name="tshirtvariant",
            name="size",
        ),
        migrations.RemoveField(
            model_name="tshirtvariant",
            name="tshirt",
        ),
        migrations.RemoveField(
            model_name="vinyl",
            name="album",
        ),
        migrations.RemoveField(
            model_name="album",
            name="external_urls",
        ),
        migrations.RemoveField(
            model_name="album",
            name="image_data",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="external_urls",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="uri",
        ),
        migrations.RemoveField(
            model_name="track",
            name="external_urls",
        ),
        migrations.RemoveField(
            model_name="track",
            name="uri",
        ),
        migrations.DeleteModel(
            name="CD",
        ),
        migrations.DeleteModel(
            name="ExternalUrl",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="TShirt",
        ),
        migrations.DeleteModel(
            name="TShirtSize",
        ),
        migrations.DeleteModel(
            name="TShirtVariant",
        ),
        migrations.DeleteModel(
            name="Vinyl",
        ),
    ]
